Repository HB9HIL/Cloudlog, pull requests merged in 2024-01, with the labels that each got.

#53 Fix issue, when starting FRESH Contest and pressing Reset QSO
  assets/js/sections/contesting.js
Labels: bug

#60 Revert magicbug/PR#2907 qrz.com
  application/models/Logbook_model.php
Labels: needs_further_investigation

#58 dupe polygon
  assets/js/sections/wajamap.js
Labels: bug

#56 Fix racecondition at contesting
  assets/js/sections/contesting.js
Labels: bug

#51 Datatables language
  application/language/bulgarian/admin_lang.php
  application/language/chinese_simplified/admin_lang.php
  application/language/czech/admin_lang.php
  application/language/dutch/admin_lang.php
  application/language/english/admin_lang.php
  application/language/finnish/admin_lang.php
  application/language/french/admin_lang.php
  application/language/german/admin_lang.php
  application/language/greek/admin_lang.php
  application/language/italian/admin_lang.php
  application/language/polish/admin_lang.php
  application/language/russian/admin_lang.php
  application/language/spanish/admin_lang.php
  application/language/swedish/admin_lang.php
  application/language/turkish/admin_lang.php
  application/views/interface_assets/footer.php
  application/views/visitor/layout/footer.php
  assets/js/sections/bandmap_list.js
  assets/js/sections/bands.js
  assets/js/sections/oqrs.js
Labels: bug

#65 Fix for WAJA in the bands, activated POTA link
  application/models/Bands.php
  application/views/bands/index.php
  application/views/interface_assets/header.php
  assets/js/sections/bands.js
Labels: bug, enhancement

#68 Added user info in admin user list
  application/language/bulgarian/admin_lang.php
  application/language/chinese_simplified/admin_lang.php
  application/language/czech/admin_lang.php
  application/language/dutch/admin_lang.php
  application/language/english/admin_lang.php
  application/language/finnish/admin_lang.php
  application/language/french/admin_lang.php
  application/language/german/admin_lang.php
  application/language/greek/admin_lang.php
  application/language/italian/admin_lang.php
  application/language/polish/admin_lang.php
  application/language/russian/admin_lang.php
  application/language/spanish/admin_lang.php
  application/language/swedish/admin_lang.php
  application/language/turkish/admin_lang.php
  application/models/User_model.php
  application/views/user/main.php
Labels: improvements

#67 [CQ Award] Switched to using geojson for the map
  application/controllers/Awards.php
  application/views/awards/cq/index.php
  application/views/interface_assets/footer.php
  assets/js/sections/cqmap.js
  assets/js/sections/cqmap_geojson.js
Labels: improvements

#78 admin last qso in user list
  application/language/bulgarian/admin_lang.php
  application/language/chinese_simplified/admin_lang.php
  application/language/czech/admin_lang.php
  application/language/dutch/admin_lang.php
  application/language/english/admin_lang.php
  application/language/finnish/admin_lang.php
  application/language/french/admin_lang.php
  application/language/german/admin_lang.php
  application/language/greek/admin_lang.php
  application/language/italian/admin_lang.php
  application/language/polish/admin_lang.php
  application/language/russian/admin_lang.php
  application/language/spanish/admin_lang.php
  application/language/swedish/admin_lang.php
  application/language/turkish/admin_lang.php
  application/models/User_model.php
  application/views/user/main.php
  assets/js/sections/user.js
Labels: improvements

#76 Add LoTW hint to search results
  application/controllers/Logbook.php
  application/views/search/result.php
Labels: improvements

#77 Prevent calling DOK-Lookup if no call is given
  assets/js/sections/qso.js
Labels: bug

#80 Load Logbook_Model everytime at search_result
  application/controllers/Logbook.php
Labels: bug

#79 Make Table great again
  assets/js/sections/user.js
Labels: enhancement, improvements

#84 Various fixes for new Users without logbook/location
  application/models/Activators_model.php
  application/models/Logbooks_model.php
  application/views/interface_assets/footer.php
Labels: bug

#83 Prevent sql injects
  application/controllers/Logbook.php
  application/models/Logbook_model.php
Labels: improvements, security

#85 Fix contest Raceconditions
  application/models/Contesting_model.php
  assets/js/sections/contesting.js
Labels: bug

#86 OTF Zipping at ADIF-Upload
  application/controllers/Adif.php
  application/models/Logbook_model.php
  application/views/adif/import.php
  application/views/interface_assets/footer.php
  assets/js/jszip.min.js
  assets/js/sections/adif.js
Labels: enhancement, improvements

#88 Removed Bug at clublog-model where OR wasn't grouped
  application/models/Clublog_model.php
Labels: bug

#92 Apply qrz.com changes to visitor's map
  application/controllers/Visitor.php
Labels: bug
